export const options = [
  {
    title: "Caixa de mensagens",
    img: "/caixa-mensagem.svg",
    alt: "Rapaz checando envelope",
    width: "109.69px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Questionários",
    img: "/questionarios.svg",
    alt: "Pessoa com dúvida",
    width: "106.79px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Pedidos de Matrícula",
    img: "/pedidos-matricula.svg",
    alt: "Moça com papelada",
    width: "182.82px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Calendário Acadêmico",
    img: "/calendario-academico.svg",
    alt: "Um calendário e uma pessoa",
    width: "137.3px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Horário Individual",
    img: "/horario-individual.svg",
    alt: "Uma pessoa consultando a hora",
    width: "102.64px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Diário",
    img: "/diario.svg",
    alt: "Um diário e uma garota",
    width: "166.18px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Material de Aula",
    img: "/material-aula.svg",
    alt: "Folhas de documento",
    width: "106.96px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Boletim",
    img: "/boletim.svg",
    alt: "Uma pessoa com uma prova nota 10",
    width: "166.18px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Estágios",
    img: "/estagio.svg",
    alt: "Duas pessoas sentadas conversando em um escritório",
    width: "168.03px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Histórico Escolar",
    img: "/historico-escolar.svg",
    alt: "Uma pessoa vendo vários documentos",
    width: "124.37px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Matriz Curricular",
    img: "/matriz-curricular.svg",
    alt: "Vários documentos verificados",
    width: "106.11px",
    height: "96px",
    rote: "/",
  },
  {
    title: "Atendimento ao Aluno",
    img: "/atendimento-aluno.svg",
    alt: "Uma pessoa falando em público",
    width: "149.09px",
    height: "96px",
    rote: "/",
  },
];
